import apiClient, { baseURL } from './api';
import { getAccessToken } from './tokenStorage';

// ── Enums ──────────────────────────────────────────────────────────────
export type CustomerType =
  | 'RetailPharmacy'
  | 'WholesalePharmacy'
  | 'OTCMedicineSeller'
  | 'Clinic'
  | 'Hospital'
  | 'ChemicalShop'
  | 'LicensedHealthFacility'
  | 'Other';

export type RelationshipType =
  | 'Owner'
  | 'Proprietor'
  | 'Director'
  | 'Manager'
  | 'PrimaryContact'
  | 'CreditResponsiblePerson'
  | 'Guarantor'
  | 'Other';

export type RegistrationStatus =
  | 'Draft'
  | 'PendingReview'
  | 'Active'
  | 'Rejected'
  | 'Suspended'
  | 'Inactive';

export type LocationType =
  | 'BusinessPremises'
  | 'DeliveryLocation'
  | 'Residential'
  | 'Other';

// ── Response types ─────────────────────────────────────────────────────
export interface CustomerPerson {
  id: string;
  fullName: string;
  relationshipType: RelationshipType;
  primaryPhoneNumber: string;
  isPrimaryContact: boolean;
  isCreditResponsiblePerson: boolean;
  portraitUrl?: string;
}

export interface CustomerLocation {
  id: string;
  latitude: number;
  longitude: number;
  accuracyMetres: number;
  landmarkAndDirections: string;
  streetAddress: string;
  regionName: string;
  districtName: string;
  captureMethod: string;
  verificationStatus: string;
  isPrimary: boolean;
}

export interface Customer {
  id: string;
  customerCode: string;
  businessName: string;
  tradingName?: string;
  customerType: CustomerType;
  registrationStatus: RegistrationStatus;
  primaryPhoneNumber: string;
  whatsAppNumber?: string;
  regionId: string;
  regionName: string;
  owningBranchId?: string;
  owningBranchName?: string;
  registeredByStaffId?: string;
  registeredByName?: string;
  registeredDuringTrekId?: string | null;
  createdOffline?: boolean;
  recordedAt?: string;
  createdAt: string;
  updatedAt?: string | null;
  primaryPerson?: CustomerPerson;
  primaryLocation?: CustomerLocation;
}

// ── Request payloads ───────────────────────────────────────────────────
export interface CreateCustomerPayload {
  businessName: string;
  tradingName?: string;
  customerType: CustomerType;
  regionId: string;
  primaryPhoneNumber: string;
  whatsAppNumber?: string;
  registeredDuringTrekId?: string | null;
  representative: {
    firstName: string;
    middleName?: string | null;
    lastName: string;
    relationshipType: RelationshipType;
    primaryPhoneNumber: string;
    ghanaCardNumber?: string;
  };
  location: {
    districtId: string;
    streetAddress: string;
    landmarkAndDirections: string;
    latitude: number;
    longitude: number;
    accuracyMetres: number;
  };
}

export interface UpdateCustomerPayload {
  businessName?: string;
  tradingName?: string;
  customerType?: CustomerType;
  regionId?: string;
  primaryPhoneNumber?: string;
  whatsAppNumber?: string;
  representative?: {
    firstName: string;
    middleName?: string | null;
    lastName: string;
    relationshipType: RelationshipType;
    primaryPhoneNumber: string;
    ghanaCardNumber?: string;
  };
  location?: {
    districtId: string;
    streetAddress?: string;
    landmarkAndDirections?: string;
    latitude?: number;
    longitude?: number;
    accuracyMetres?: number;
  };
}

export interface AddLocationPayload {
  locationType?: LocationType;
  regionId: string;
  districtId: string;
  landmarkAndDirections: string;
  streetAddress?: string;
  latitude?: number;
  longitude?: number;
  accuracyMetres?: number;
  isPrimary?: boolean;
}

export type LedgerEntryType = 'Debit' | 'Credit';

export interface LedgerEntry {
  id: string;
  entryType: LedgerEntryType;
  amount: number;
  paymentMethod?: string | null;
  description: string;
  trekId?: string | null;
  trekNumber?: string | null;
  isAutoGenerated: boolean;
  recordedAt: string;
  recordedBy: string;
}

export interface LedgerResponse {
  customerId: string;
  totalDebits: number;
  totalCredits: number;
  currentBalance: number;
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages: number;
  entries: LedgerEntry[];
}

export interface LedgerSummaryCustomer {
  customerId: string;
  customerCode: string;
  businessName: string;
  primaryPhoneNumber: string;
  regionName: string;
  branchName?: string;
  totalDebits: number;
  totalCredits: number;
  currentBalance: number;
}

export interface LedgerSummaryResponse {
  totalOutstanding: number;
  customersWithBalance: number;
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages: number;
  customers: LedgerSummaryCustomer[];
}

export interface AddLedgerEntryPayload {
  entryType: LedgerEntryType;
  amount: number;
  paymentMethod?: string;
  description: string;
  recordedAt?: string;
}

export interface CustomerMapPin {
  customerAccountId: string;
  customerCode: string;
  businessName: string;
  tradingName?: string;
  customerType: CustomerType;
  registrationStatus: RegistrationStatus;
  primaryPhoneNumber: string;
  latitude: number;
  longitude: number;
  accuracyMetres?: number;
  streetAddress?: string;
  landmarkAndDirections?: string;
  branchId?: string;
  branchName?: string;
  regionId?: string;
  regionName?: string;
  primaryContactName?: string;
  primaryContactPhone?: string;
  primaryContactPortraitUrl?: string;
}

// ── API ────────────────────────────────────────────────────────────────
export const customersApi = {
  getMapPins: async (params?: { branchId?: string; regionId?: string }): Promise<CustomerMapPin[]> => {
    const res = await apiClient.get<CustomerMapPin[]>('/customers/map-pins', { params });
    return res.data;
  },

  getCustomers: async (params?: {
    search?: string;
    sort?: string;
    pageNumber?: number;
    pageSize?: number;
    regionId?: string;
    districtId?: string;
    branchId?: string;
    customerType?: string;
    status?: string;
  }) => {
    const res = await apiClient.get<any>('/customers', { params });
    return res.data;
  },

  getCustomer: async (id: string): Promise<Customer> => {
    const res = await apiClient.get<Customer>(`/customers/${id}`);
    return res.data;
  },

  createCustomer: async (payload: CreateCustomerPayload): Promise<Customer> => {
    const res = await apiClient.post<Customer>('/customers', payload);
    return res.data;
  },

  updateCustomer: async (id: string, payload: UpdateCustomerPayload): Promise<Customer> => {
    const res = await apiClient.patch<Customer>(`/customers/${id}`, payload);
    return res.data;
  },

  addLocation: async (customerId: string, payload: AddLocationPayload) => {
    const res = await apiClient.post(`/customers/${customerId}/locations`, payload);
    return res.data;
  },

  uploadPortrait: async (customerId: string, personId: string, file: File) => {
    const formData = new FormData();
    formData.append('file', file);
    const res = await apiClient.post(
      `/customers/${customerId}/people/${personId}/portrait`,
      formData,
      { headers: { 'Content-Type': 'multipart/form-data' } }
    );
    return res.data;
  },

  getLedger: async (customerId: string, params?: { entryType?: string; pageNumber?: number; pageSize?: number }): Promise<LedgerResponse> => {
    const res = await apiClient.get<LedgerResponse>(`/customers/${customerId}/ledger`, { params });
    return res.data;
  },

  addLedgerEntry: async (customerId: string, payload: AddLedgerEntryPayload): Promise<LedgerEntry> => {
    const res = await apiClient.post<LedgerEntry>(`/customers/${customerId}/ledger`, payload);
    return res.data;
  },

  getLedgerSummary: async (params?: {
    hasBalance?: boolean;
    search?: string;
    sort?: string;
    branchId?: string;
    regionId?: string;
    pageNumber?: number;
    pageSize?: number;
  }): Promise<LedgerSummaryResponse> => {
    const res = await apiClient.get<LedgerSummaryResponse>('/ledger/summary', { params });
    return res.data;
  },

  exportLedgerSummary: async (params?: {
    from?: string;
    to?: string;
    hasBalance?: boolean;
    branchId?: string;
    regionId?: string;
  }): Promise<{ blob: Blob; filename: string }> => {
    const query = new URLSearchParams();
    if (params?.from) query.set('from', params.from);
    if (params?.to) query.set('to', params.to);
    if (params?.hasBalance) query.set('hasBalance', 'true');
    if (params?.branchId) query.set('branchId', params.branchId);
    if (params?.regionId) query.set('regionId', params.regionId);
    const qs = query.toString();
    const response = await fetch(`${baseURL}/ledger/export${qs ? `?${qs}` : ''}`, {
      headers: { Authorization: `Bearer ${getAccessToken()}` },
    });
    if (!response.ok) throw new Error(`Export failed: ${response.status}`);
    const disposition = response.headers.get('Content-Disposition');
    const filename = disposition?.match(/filename="?([^";]+)"?/)?.[1] ?? 'LedgerSummary.xlsx';
    const blob = await response.blob();
    return { blob, filename };
  },

  exportCustomerLedger: async (
    customerId: string,
    params?: { from?: string; to?: string },
  ): Promise<{ blob: Blob; filename: string }> => {
    const query = new URLSearchParams();
    if (params?.from) query.set('from', params.from);
    if (params?.to) query.set('to', params.to);
    const qs = query.toString();
    const response = await fetch(
      `${baseURL}/customers/${customerId}/ledger/export${qs ? `?${qs}` : ''}`,
      { headers: { Authorization: `Bearer ${getAccessToken()}` } }
    );
    if (!response.ok) throw new Error(`Export failed: ${response.status}`);
    const disposition = response.headers.get('Content-Disposition');
    const filename = disposition?.match(/filename="?([^";]+)"?/)?.[1] ?? 'Ledger.xlsx';
    const blob = await response.blob();
    return { blob, filename };
  },
};
